name: build

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: ubuntu-latest
        node: 12
    name: Test ${{ matrix.os }}/${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --cwd "merch-dropper" install
      - run: yarn --cwd "merch-dropper" test
        env:
          CI: true
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: yarn --cwd "merch-dropper" install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          CI: true
        with:
          coverageCommand: yarn --cwd "merch-dropper" cypress:coverage
          coverageLocations: "merch-dropper/coverage/lcov.info:lcov"
          debug: true
