name: build

on: [push, pull_request]

jobs:
  coverage:
    name: Test and publish test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "12"
      - run: yarn --cwd "merch-dropper" install
      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          CI: true
          REACT_APP_BASE_URL: development
        with:
          coverageCommand: yarn --cwd "merch-dropper" cypress:coverage
          # Need to use Clover, as NYC lcov generator doesn't support absolute paths
          coverageLocations: "${{github.workspace}}/merch-dropper/coverage/clover.xmlinfo:clover"
          debug: true
